apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smarbeidsgiver-pdfgenrs
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  observability:
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 15m
      memory: 128Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfosmaltinn
          namespace: teamsykmelding
          cluster: dev-gcp
